/**
 * Style injection for UniversalPicker.
 * @module styles
 */

var stylesInjected = false;

export function injectStyles(theme) {
    if (stylesInjected) return;
    stylesInjected = true;

    var css = [
        '.up-picker {',
        '  position: absolute;',
        '  display: none;',
        '  background: ' + theme.bgColor + ';',
        '  border: 1px solid ' + theme.borderColor + ';',
        '  border-radius: 12px;',
        '  box-shadow: 0 12px 40px rgba(0,0,0,0.12), 0 4px 12px rgba(0,0,0,0.08);',
        '  z-index: 99999;',
        '  font-family: ' + theme.fontFamily + ';',
        '  user-select: none;',
        '  -webkit-user-select: none;',
        '  color: ' + theme.textColor + ';',
        '  line-height: 1.4;',
        '  box-sizing: border-box;',
        '}',
        '.up-picker *, .up-picker *::before, .up-picker *::after {',
        '  box-sizing: border-box;',
        '}',
        '.up-picker.up-show {',
        '  display: flex;',
        '  animation: upFadeIn 0.15s ease-out;',
        '}',
        '@keyframes upFadeIn {',
        '  from { opacity: 0; transform: translateY(-4px); }',
        '  to { opacity: 1; transform: translateY(0); }',
        '}',
        '',
        '.up-sidebar {',
        '  padding: 12px;',
        '  border-right: 1px solid ' + theme.borderColor + ';',
        '  display: flex;',
        '  flex-direction: column;',
        '  min-width: 160px;',
        '  background: ' + theme.sidebarBg + ';',
        '  border-radius: 12px 0 0 12px;',
        '  gap: 2px;',
        '}',
        '.up-sidebar-item {',
        '  padding: 9px 14px;',
        '  font-size: 13px;',
        '  font-weight: 500;',
        '  border-radius: 6px;',
        '  cursor: pointer;',
        '  color: ' + theme.textColor + ';',
        '  transition: background 0.15s, color 0.15s;',
        '  white-space: nowrap;',
        '}',
        '.up-sidebar-item:hover {',
        '  background: ' + theme.rangeColor + ';',
        '  color: ' + theme.primaryColor + ';',
        '}',
        '.up-sidebar-item.active {',
        '  background: ' + theme.primaryColor + ';',
        '  color: #fff;',
        '}',
        '',
        '.up-main {',
        '  display: flex;',
        '  flex-direction: column;',
        '  background: ' + theme.bgColor + ';',
        '  border-radius: 0 12px 12px 0;',
        '  overflow: hidden;',
        '}',
        '.up-picker:not(.up-has-sidebar) .up-main {',
        '  border-radius: 12px;',
        '}',
        '',
        '.up-nav {',
        '  display: flex;',
        '  justify-content: space-between;',
        '  align-items: center;',
        '  padding: 14px 20px;',
        '  border-bottom: 1px solid ' + theme.borderColor + ';',
        '}',
        '.up-nav-title {',
        '  font-weight: 700;',
        '  font-size: 14px;',
        '  color: ' + theme.primaryColor + ';',
        '  letter-spacing: -0.01em;',
        '}',
        '.up-btn-nav {',
        '  background: ' + theme.bgColor + ';',
        '  border: 1px solid ' + theme.borderColor + ';',
        '  border-radius: 6px;',
        '  cursor: pointer;',
        '  padding: 6px 12px;',
        '  font-size: 12px;',
        '  color: ' + theme.textColor + ';',
        '  transition: background 0.15s, border-color 0.15s;',
        '  line-height: 1;',
        '}',
        '.up-btn-nav:hover {',
        '  background: #f1f5f9;',
        '  border-color: #cbd5e1;',
        '}',
        '.up-btn-nav:disabled {',
        '  opacity: 0.35;',
        '  cursor: not-allowed;',
        '}',
        '',
        '.up-panes {',
        '  display: flex;',
        '  justify-content: center;',
        '  gap: 28px;',
        '  padding: 20px 24px;',
        '}',
        '.up-month-box {',
        '  width: 224px;',
        '}',
        '.up-month-title {',
        '  text-align: center;',
        '  font-weight: 700;',
        '  font-size: 12px;',
        '  margin-bottom: 12px;',
        '  color: #64748b;',
        '  text-transform: uppercase;',
        '  letter-spacing: 0.05em;',
        '}',
        '',
        '.up-grid {',
        '  display: grid;',
        '  grid-template-columns: repeat(7, 32px);',
        '  gap: 0;',
        '}',
        '.up-grid.up-has-weeknum {',
        '  grid-template-columns: 28px repeat(7, 32px);',
        '}',
        '.up-head {',
        '  text-align: center;',
        '  font-size: 10px;',
        '  color: #94a3b8;',
        '  font-weight: 700;',
        '  height: 32px;',
        '  display: flex;',
        '  align-items: center;',
        '  justify-content: center;',
        '  text-transform: uppercase;',
        '  letter-spacing: 0.05em;',
        '}',
        '.up-weeknum {',
        '  font-size: 10px;',
        '  color: #cbd5e1;',
        '  display: flex;',
        '  align-items: center;',
        '  justify-content: center;',
        '  font-weight: 600;',
        '}',
        '',
        '.up-day {',
        '  width: 32px;',
        '  height: 32px;',
        '  display: flex;',
        '  align-items: center;',
        '  justify-content: center;',
        '  font-size: 12px;',
        '  font-weight: 500;',
        '  cursor: pointer;',
        '  transition: background 0.1s, color 0.1s;',
        '  position: relative;',
        '  z-index: 1;',
        '  border-radius: 4px;',
        '}',
        '.up-day:hover:not(.up-outside):not(.up-disabled) {',
        '  background: ' + theme.primaryColor + ';',
        '  color: #fff;',
        '}',
        '.up-day.up-today:not(.up-selected) {',
        '  font-weight: 800;',
        '  color: ' + theme.primaryColor + ';',
        '}',
        '.up-day.up-today:not(.up-selected)::after {',
        '  content: "";',
        '  position: absolute;',
        '  bottom: 3px;',
        '  left: 50%;',
        '  transform: translateX(-50%);',
        '  width: 4px;',
        '  height: 4px;',
        '  border-radius: 50%;',
        '  background: ' + theme.primaryColor + ';',
        '}',
        '.up-day.up-selected {',
        '  background: ' + theme.primaryColor + ' !important;',
        '  color: #fff !important;',
        '  border-radius: 4px;',
        '  font-weight: 700;',
        '}',
        '.up-day.up-in-range {',
        '  background: ' + theme.rangeColor + ';',
        '  border-radius: 0;',
        '  color: ' + theme.primaryColor + ';',
        '}',
        '.up-day.up-range-start {',
        '  border-radius: 4px 0 0 4px;',
        '}',
        '.up-day.up-range-end {',
        '  border-radius: 0 4px 4px 0;',
        '}',
        '.up-day.up-outside {',
        '  color: #d1d5db;',
        '  cursor: default;',
        '  pointer-events: none;',
        '}',
        '.up-day.up-disabled {',
        '  color: #e2e8f0;',
        '  cursor: not-allowed;',
        '  text-decoration: line-through;',
        '  pointer-events: none;',
        '}',
        '',
        '.up-doubledate-grid {',
        '  display: grid;',
        '  grid-template-columns: repeat(3, 1fr);',
        '  gap: 10px;',
        '  padding: 24px;',
        '  min-width: 320px;',
        '}',
        '.up-dd-item {',
        '  padding: 16px 12px;',
        '  border: 1px solid ' + theme.borderColor + ';',
        '  border-radius: 8px;',
        '  cursor: pointer;',
        '  text-align: center;',
        '  font-weight: 700;',
        '  font-size: 15px;',
        '  color: ' + theme.textColor + ';',
        '  transition: all 0.15s;',
        '}',
        '.up-dd-item:hover {',
        '  border-color: ' + theme.primaryColor + ';',
        '  background: ' + theme.rangeColor + ';',
        '  color: ' + theme.primaryColor + ';',
        '  transform: translateY(-1px);',
        '  box-shadow: 0 2px 8px rgba(0,0,0,0.06);',
        '}',
        '.up-dd-item.up-dd-selected {',
        '  background: ' + theme.primaryColor + ';',
        '  color: #fff;',
        '  border-color: ' + theme.primaryColor + ';',
        '}',
        '',
        '.up-footer {',
        '  padding: 12px 20px;',
        '  border-top: 1px solid ' + theme.borderColor + ';',
        '  display: flex;',
        '  justify-content: space-between;',
        '  align-items: center;',
        '  background: #fcfcfd;',
        '  border-radius: 0 0 12px 0;',
        '  gap: 12px;',
        '}',
        '.up-picker:not(.up-has-sidebar) .up-footer {',
        '  border-radius: 0 0 12px 12px;',
        '}',
        '.up-footer-info {',
        '  font-size: 12px;',
        '  color: #94a3b8;',
        '  font-weight: 500;',
        '}',
        '.up-footer-actions {',
        '  display: flex;',
        '  gap: 8px;',
        '}',
        '.up-btn {',
        '  border: none;',
        '  padding: 8px 20px;',
        '  border-radius: 6px;',
        '  cursor: pointer;',
        '  font-weight: 600;',
        '  font-size: 13px;',
        '  transition: background 0.15s, opacity 0.15s;',
        '  font-family: inherit;',
        '}',
        '.up-btn-apply {',
        '  background: ' + theme.primaryColor + ';',
        '  color: #fff;',
        '}',
        '.up-btn-apply:hover {',
        '  opacity: 0.9;',
        '}',
        '.up-btn-apply:disabled {',
        '  opacity: 0.4;',
        '  cursor: not-allowed;',
        '}',
        '.up-btn-cancel {',
        '  background: #f1f5f9;',
        '  color: #64748b;',
        '}',
        '.up-btn-cancel:hover {',
        '  background: #e2e8f0;',
        '}',
        '',
        '.up-dropdown-row {',
        '  display: flex;',
        '  justify-content: center;',
        '  gap: 8px;',
        '  margin-bottom: 12px;',
        '}',
        '.up-select {',
        '  padding: 4px 8px;',
        '  border: 1px solid ' + theme.borderColor + ';',
        '  border-radius: 4px;',
        '  font-size: 12px;',
        '  font-family: inherit;',
        '  color: ' + theme.textColor + ';',
        '  background: #fff;',
        '  cursor: pointer;',
        '  outline: none;',
        '}',
        '.up-select:focus {',
        '  border-color: ' + theme.primaryColor + ';',
        '}',
        '',
        '/* Time Picker */',
        '.up-time-row {',
        '  display: flex;',
        '  justify-content: center;',
        '  align-items: center;',
        '  gap: 24px;',
        '  padding: 12px 20px;',
        '  border-top: 1px solid ' + theme.borderColor + ';',
        '  background: #fafbfc;',
        '}',
        '.up-time-group {',
        '  display: flex;',
        '  align-items: center;',
        '  gap: 6px;',
        '}',
        '.up-time-label {',
        '  font-size: 11px;',
        '  font-weight: 600;',
        '  color: #64748b;',
        '  text-transform: uppercase;',
        '  letter-spacing: 0.05em;',
        '  margin-right: 4px;',
        '}',
        '.up-time-sep {',
        '  font-size: 13px;',
        '  font-weight: 700;',
        '  color: #94a3b8;',
        '}',
        '.up-time-select {',
        '  padding: 4px 6px;',
        '  min-width: 48px;',
        '  text-align: center;',
        '}',
        '',
        '@media (max-width: 680px) {',
        '  .up-picker {',
        '    flex-direction: column;',
        '    width: calc(100vw - 20px) !important;',
        '    left: 10px !important;',
        '    right: 10px !important;',
        '  }',
        '  .up-sidebar {',
        '    flex-direction: row;',
        '    overflow-x: auto;',
        '    border-right: none;',
        '    border-bottom: 1px solid ' + theme.borderColor + ';',
        '    border-radius: 12px 12px 0 0;',
        '    min-width: unset;',
        '  }',
        '  .up-main {',
        '    border-radius: 0 0 12px 12px;',
        '  }',
        '  .up-panes {',
        '    flex-direction: column;',
        '    align-items: center;',
        '    gap: 16px;',
        '    padding: 16px;',
        '  }',
        '  .up-footer {',
        '    border-radius: 0 0 12px 12px;',
        '  }',
        '}'
    ].join('\n');

    var style = document.createElement('style');
    style.id = 'universal-picker-styles';
    style.type = 'text/css';
    style.appendChild(document.createTextNode(css));
    document.head.appendChild(style);
}
